export type SomaliaCity = { name: string; district: string; region: string; lat: number; lng: number };

export const SOMALIA_CITIES: SomaliaCity[] = [
  { name: 'Mogadishu',                district: 'Hodan',            region: 'Banaadir',            lat: 2.0469,  lng: 45.3182 },
  { name: 'Mogadishu – Wadajir',      district: 'Wadajir',          region: 'Banaadir',            lat: 2.0560,  lng: 45.3100 },
  { name: 'Mogadishu – Wardhiigleey', district: 'Wardhiigleey',     region: 'Banaadir',            lat: 2.0450,  lng: 45.3250 },
  { name: 'Mogadishu – Yaqshid',      district: 'Yaqshid',          region: 'Banaadir',            lat: 2.0620,  lng: 45.3350 },
  { name: 'Mogadishu – Bondhere',     district: 'Bondhere',         region: 'Banaadir',            lat: 2.0490,  lng: 45.3420 },
  { name: 'Mogadishu – Shangaani',    district: 'Shangaani',        region: 'Banaadir',            lat: 2.0380,  lng: 45.3270 },
  { name: 'Hargeisa',                 district: 'Hargeisa',         region: 'Woqooyi Galbeed',     lat: 9.5600,  lng: 44.0650 },
  { name: 'Bosaso',                   district: 'Bosaaso',          region: 'Bari',                lat: 11.2846, lng: 49.1778 },
  { name: 'Kismayo',                  district: 'Kismaayo',         region: 'Jubbada Hoose',       lat: -0.3578, lng: 42.5454 },
  { name: 'Berbera',                  district: 'Berbera',          region: 'Woqooyi Galbeed',     lat: 10.4396, lng: 45.0143 },
  { name: 'Gaalkacyo',                district: 'Gaalkacyo Waqooyi',region: 'Mudug',               lat: 6.7696,  lng: 47.4329 },
  { name: 'Baydhabo',                 district: 'Baydhabo',         region: 'Bay',                 lat: 3.1169,  lng: 43.6500 },
  { name: 'Marka',                    district: 'Marka',            region: 'Shabeellaha Hoose',   lat: 1.7161,  lng: 44.7716 },
  { name: 'Jawhar',                   district: 'Jawhar',           region: 'Shabeellaha Dhexe',   lat: 2.7798,  lng: 45.5001 },
  { name: 'Garowe',                   district: 'Garowe',           region: 'Nugaal',              lat: 8.4054,  lng: 48.4845 },
  { name: 'Laascaanood',              district: 'Laascaanood',      region: 'Sool',                lat: 8.4699,  lng: 47.3592 },
  { name: 'Burco',                    district: 'Burco',            region: 'Togdheer',            lat: 9.5250,  lng: 45.5328 },
  { name: 'Beledweyne',               district: 'Beledweyne',       region: 'Hiiraan',             lat: 4.7360,  lng: 45.2041 },
  { name: 'Dhuusamarreeb',            district: 'Dhuusamarreeb',    region: 'Galgaduud',           lat: 5.5330,  lng: 46.3760 },
  { name: 'Afgooye',                  district: 'Afgooye',          region: 'Shabeellaha Hoose',   lat: 2.1419,  lng: 45.1221 },
  { name: 'Luuq',                     district: 'Luuq',             region: 'Gedo',                lat: 3.8027,  lng: 42.5426 },
  { name: 'Baraawe',                  district: 'Baraawe',          region: 'Shabeellaha Hoose',   lat: 1.1078,  lng: 44.0309 },
  { name: 'Borama',                   district: 'Borama',           region: 'Awdal',               lat: 9.9361,  lng: 43.1826 },
  { name: 'Ceerigaavo',               district: 'Ceerigaavo',       region: 'Sanaag',              lat: 10.6247, lng: 47.3690 },
  { name: 'Jilib',                    district: 'Jilib',            region: 'Jubbada Dhexe',       lat: 0.4872,  lng: 42.7812 },
  { name: "Bu'aale",                  district: "Bu'aale",          region: 'Jubbada Dhexe',       lat: 1.0833,  lng: 42.5833 },
  { name: 'Doolow',                   district: 'Doolow',           region: 'Gedo',                lat: 4.1756,  lng: 42.0792 },
  { name: 'Jamaame',                  district: 'Jamaame',          region: 'Jubbada Hoose',       lat: 0.0667,  lng: 42.7500 },
  { name: 'Ceeldheer',                district: 'Ceeldheer',        region: 'Galgaduud',           lat: 4.7652,  lng: 46.6200 },
  { name: 'Xuddur',                   district: 'Xuddur',           region: 'Bakool',              lat: 4.1196,  lng: 43.8888 },
  { name: 'Qardho',                   district: 'Qardho',           region: 'Bari',                lat: 9.5000,  lng: 49.0833 },
  { name: 'Baardheere',               district: 'Baardheere',       region: 'Gedo',                lat: 2.3427,  lng: 42.2740 },
  { name: 'Wanlaweyn',                district: 'Wanlaweyn',        region: 'Shabeellaha Hoose',   lat: 2.6194,  lng: 44.8950 },
  { name: 'Diinsoor',                 district: 'Diinsoor',         region: 'Bay',                 lat: 2.4000,  lng: 42.9833 },
  { name: 'Taleex',                   district: 'Taleex',           region: 'Sool',                lat: 8.3333,  lng: 47.7500 },
  { name: 'Hobyo',                    district: 'Hobyo',            region: 'Mudug',               lat: 5.3500,  lng: 48.5250 },
  { name: 'Eyl',                      district: 'Eyl',              region: 'Nugaal',              lat: 7.9803,  lng: 49.8167 },
  { name: 'Caynabo',                  district: 'Caynabo',          region: 'Togdheer',            lat: 8.9833,  lng: 46.9667 },
  { name: 'Oodweyne',                 district: 'Oodweyne',         region: 'Togdheer',            lat: 9.4078,  lng: 45.0618 },
  { name: 'Zeylac',                   district: 'Zeylac',           region: 'Awdal',               lat: 11.3597, lng: 43.4699 },
  { name: 'Baki',                     district: 'Baki',             region: 'Awdal',               lat: 10.1986, lng: 43.4785 },
  { name: 'Lughaye',                  district: 'Lughaye',          region: 'Awdal',               lat: 10.5722, lng: 43.8961 },
  { name: 'Laasqoray',                district: 'Laasqoray',        region: 'Sanaag',              lat: 11.1667, lng: 48.1833 },
  { name: 'Ceel Afweyn',              district: 'Ceel Afweyn',      region: 'Sanaag',              lat: 10.4307, lng: 47.0696 },
  { name: 'Garadag',                  district: 'Garadag',          region: 'Mudug',               lat: 6.2167,  lng: 47.2167 },
  { name: 'Xarardheere',              district: 'Xarardheere',      region: 'Mudug',               lat: 4.7369,  lng: 48.1758 },
  { name: 'Qansax Dheere',            district: 'Qansax Dheere',    region: 'Bay',                 lat: 3.7833,  lng: 43.5000 },
  { name: 'Belet Xaawo',              district: 'Belet Xaawo',      region: 'Gedo',                lat: 4.5170,  lng: 42.0756 },
];
